/**
 * Real-world scenarios demonstrating MCPilot SDK Core usage
 * These examples show practical applications of the SDK
 */

import { createSDK, MCPilotSDK, EnhancedRuntimeDetector, ToolRegistry, discoverLocalMCPServers } from '@mcpilotx/intentorch';

// ==================== Scenario 1: Project Setup Assistant ====================

async function projectSetupAssistant() {
  console.log('=== Scenario 1: Project Setup Assistant ===\n');
  
  const sdk = createSDK();
  
  console.log('1. Detecting project type...');
  const detection = await EnhancedRuntimeDetector.detect('.');
  console.log(`   Detected: ${detection.runtime} project`);
  
  console.log('\n2. Analyzing project structure...');
  // In a real scenario, you would analyze package.json, requirements.txt, etc.
  console.log('   Project analysis complete');
  
  console.log('\n3. Recommending development tools...');
  const recommendations = {
    node: ['ESLint', 'Prettier', 'Jest', 'TypeScript'],
    python: ['Black', 'Flake8', 'Pytest', 'Mypy'],
    docker: ['Docker Compose', 'Health checks', 'Multi-stage builds']
  };
  
  const recommendedTools = recommendations[detection.runtime as keyof typeof recommendations] || [];
  console.log(`   Recommended tools: ${recommendedTools.join(', ')}`);
  
  console.log('\n4. Generating setup script...');
  const setupScript = `#!/bin/bash
# ${detection.runtime.toUpperCase()} Project Setup Script
# Generated by MCPilot SDK

echo "Setting up ${detection.runtime} project..."

# Install dependencies
${detection.runtime === 'node' ? 'npm install' : detection.runtime === 'python' ? 'pip install -r requirements.txt' : '# Docker setup'}

# Setup development tools
${recommendedTools.map(tool => `# Setup ${tool}`).join('\n')}

echo "Project setup complete!"`;
  
  console.log('   Setup script generated');
  console.log('\n' + setupScript);
  
  console.log('\n✅ Project setup assistant completed\n');
}

// ==================== Scenario 2: Code Quality Checker ====================

async function codeQualityChecker() {
  console.log('=== Scenario 2: Code Quality Checker ===\n');
  
  const sdk = createSDK();
  
  console.log('1. Registering code analysis tools...');
  
  // Register a code complexity analyzer tool
  sdk.toolRegistry.registerTool({
    name: 'analyze_code_complexity',
    description: 'Analyze code complexity metrics',
    inputSchema: {
      type: 'object',
      properties: {
        filePath: { type: 'string' },
        language: { type: 'string' }
      },
      required: ['filePath']
    }
  }, async (args: any) => {
    // Simulate code complexity analysis
    const metrics = {
      cyclomaticComplexity: Math.floor(Math.random() * 20) + 1,
      cognitiveComplexity: Math.floor(Math.random() * 30) + 1,
      linesOfCode: Math.floor(Math.random() * 500) + 50,
      maintainabilityIndex: Math.floor(Math.random() * 100) + 1
    };
    
    return {
      metrics,
      suggestions: metrics.cyclomaticComplexity > 10 ? 
        'Consider refactoring to reduce complexity' : 
        'Complexity is within acceptable limits'
    };
  }, 'code-analysis', 'complexity-tool');
  
  console.log('✅ Code analysis tools registered');
  
  console.log('\n2. Analyzing sample files...');
  
  const filesToAnalyze = [
    { path: 'src/main.ts', language: 'typescript' },
    { path: 'src/utils.js', language: 'javascript' },
    { path: 'tests/test_suite.py', language: 'python' }
  ];
  
  for (const file of filesToAnalyze) {
    try {
      const result = await sdk.executeTool('analyze_code_complexity', file);
      console.log(`\n   File: ${file.path}`);
      console.log(`   Complexity: ${result.metrics.cyclomaticComplexity}`);
      console.log(`   Maintainability: ${result.metrics.maintainabilityIndex}/100`);
      console.log(`   Suggestion: ${result.text}`);
    } catch (error: any) {
      console.log(`   Error analyzing ${file.path}: ${error.message}`);
    }
  }
  
  console.log('\n✅ Code quality check completed\n');
}

// ==================== Scenario 3: API Integration Assistant ====================

async function apiIntegrationAssistant() {
  console.log('=== Scenario 3: API Integration Assistant ===\n');
  
  const sdk = createSDK();
  
  console.log('1. Discovering available APIs...');
  
  // Register mock API tools
  const mockApis = [
    {
      name: 'weather_api',
      description: 'Get weather information for a location',
      endpoint: 'https://api.weather.example.com/v1/forecast'
    },
    {
      name: 'currency_api',
      description: 'Convert between currencies',
      endpoint: 'https://api.currency.example.com/v1/convert'
    },
    {
      name: 'news_api',
      description: 'Get latest news headlines',
      endpoint: 'https://api.news.example.com/v1/articles'
    }
  ];
  
  mockApis.forEach(api => {
    sdk.toolRegistry.registerTool({
      name: api.name,
      description: api.description,
      inputSchema: {
        type: 'object',
        properties: {
          query: { type: 'string' }
        },
        required: ['query']
      }
    }, async (args: any) => {
      // Simulate API response
      return {
        data: `Mock response from ${api.endpoint} for query: "${args.query}"`,
        timestamp: new Date().toISOString(),
        status: 'success'
      };
    }, 'api-integration', `${api.name}-tool`);
  });
  
  console.log(`✅ Discovered ${mockApis.length} APIs`);
  
  console.log('\n2. Testing API integrations...');
  
  const testQueries = [
    { api: 'weather_api', query: 'New York' },
    { api: 'currency_api', query: 'USD to EUR' },
    { api: 'news_api', query: 'technology' }
  ];
  
  for (const test of testQueries) {
    try {
      const result = await sdk.executeTool(test.api, { query: test.query });
      console.log(`\n   API: ${test.api}`);
      console.log(`   Query: "${test.query}"`);
      console.log(`   Response: ${result.data.substring(0, 50)}...`);
    } catch (error: any) {
      console.log(`   Error with ${test.api}: ${error.message}`);
    }
  }
  
  console.log('\n3. Generating integration code...');
  
  const integrationCode = `// API Integration Code
// Generated by MCPilot SDK

const apiConfig = {
  weather: {
    endpoint: 'https://api.weather.example.com/v1/forecast',
    apiKey: process.env.WEATHER_API_KEY
  },
  currency: {
    endpoint: 'https://api.currency.example.com/v1/convert',
    apiKey: process.env.CURRENCY_API_KEY
  },
  news: {
    endpoint: 'https://api.news.example.com/v1/articles',
    apiKey: process.env.NEWS_API_KEY
  }
};

// Usage example
async function getWeather(location) {
  const response = await fetch(\`\${apiConfig.weather.endpoint}?location=\${location}\`, {
    headers: { 'Authorization': \`Bearer \${apiConfig.weather.apiKey}\` }
  });
  return await response.json();
}`;
  
  console.log('   Integration code generated');
  console.log('\n' + integrationCode);
  
  console.log('\n✅ API integration assistant completed\n');
}

// ==================== Scenario 4: DevOps Automation ====================

async function devopsAutomation() {
  console.log('=== Scenario 4: DevOps Automation ===\n');
  
  const sdk = createSDK();
  
  console.log('1. Setting up DevOps tools...');
  
  // Register DevOps tools
  const devopsTools = [
    {
      name: 'deploy_service',
      description: 'Deploy a service to production',
      category: 'deployment'
    },
    {
      name: 'rollback_deployment',
      description: 'Rollback a failed deployment',
      category: 'deployment'
    },
    {
      name: 'check_service_health',
      description: 'Check health status of deployed services',
      category: 'monitoring'
    },
    {
      name: 'scale_service',
      description: 'Scale service instances up or down',
      category: 'scaling'
    }
  ];
  
  devopsTools.forEach(tool => {
    sdk.toolRegistry.registerTool({
      name: tool.name,
      description: tool.description,
      inputSchema: {
        type: 'object',
        properties: {
          serviceName: { type: 'string' },
          environment: { type: 'string', enum: ['staging', 'production'] }
        },
        required: ['serviceName']
      }
    }, async (args: any) => {
      // Simulate DevOps operation
      const operations = {
        deploy_service: `Deploying ${args.serviceName} to ${args.environment || 'production'}`,
        rollback_deployment: `Rolling back ${args.serviceName} deployment`,
        check_service_health: `Checking health of ${args.serviceName}`,
        scale_service: `Scaling ${args.serviceName}`
      };
      
      return {
        operation: operations[tool.name as keyof typeof operations],
        status: 'success',
        timestamp: new Date().toISOString(),
        details: {
          service: args.serviceName,
          environment: args.environment || 'production',
          action: tool.name
        }
      };
    }, 'devops-automation', `${tool.name}-tool`);
  });
  
  console.log(`✅ ${devopsTools.length} DevOps tools registered`);
  
  console.log('\n2. Simulating deployment pipeline...');
  
  const deploymentSteps = [
    { tool: 'check_service_health', params: { serviceName: 'api-service', environment: 'staging' } },
    { tool: 'deploy_service', params: { serviceName: 'api-service', environment: 'staging' } },
    { tool: 'check_service_health', params: { serviceName: 'api-service', environment: 'staging' } },
    { tool: 'scale_service', params: { serviceName: 'api-service', environment: 'staging' } }
  ];
  
  for (const step of deploymentSteps) {
    try {
      console.log(`\n   Step: ${step.tool}`);
      const result = await sdk.executeTool(step.tool, step.params);
      console.log(`   Result: ${result.operation}`);
      console.log(`   Status: ${result.status}`);
      
      // Simulate delay between steps
      await new Promise(resolve => setTimeout(resolve, 500));
    } catch (error: any) {
      console.log(`   Error: ${error.message}`);
      
      // If deployment fails, trigger rollback
      if (step.tool === 'deploy_service') {
        console.log('   Triggering rollback...');
        try {
          const rollbackResult = await sdk.executeTool('rollback_deployment', step.params);
          console.log(`   Rollback: ${rollbackResult.operation}`);
        } catch (rollbackError: any) {
          console.log(`   Rollback failed: ${rollbackError.message}`);
        }
      }
    }
  }
  
  console.log('\n3. Generating deployment report...');
  
  const report = {
    deploymentId: `deploy-${Date.now()}`,
    service: 'api-service',
    environment: 'staging',
    steps: deploymentSteps.length,
    completedAt: new Date().toISOString(),
    status: 'completed'
  };
  
  console.log('   Deployment report generated:');
  console.log(JSON.stringify(report, null, 2));
  
  console.log('\n✅ DevOps automation completed\n');
}

// ==================== Main Function ====================

async function main() {
  console.log('🚀 MCPilot SDK Core - Real World Scenarios\n');
  console.log('Demonstrating practical applications of the SDK...\n');
  
  try {
    await projectSetupAssistant();
    await codeQualityChecker();
    await apiIntegrationAssistant();
    await devopsAutomation();
    
    console.log('🎉 All scenarios completed successfully!');
    console.log('\n📋 Summary:');
    console.log('1. Project Setup Assistant - Automated project analysis and setup');
    console.log('2. Code Quality Checker - Code complexity analysis and recommendations');
    console.log('3. API Integration Assistant - API discovery and integration code generation');
    console.log('4. DevOps Automation - Automated deployment pipeline simulation');
    console.log('\n💡 These scenarios demonstrate how MCPilot SDK Core can be used');
    console.log('   to build practical, real-world applications.');
    
  } catch (error) {
    console.error('Error running scenarios:', error);
    process.exit(1);
  }
}

// Run all scenarios
main().catch(console.error);